language: node_js

node_js:
  - '6.11.1'
  - '7'
  
branches:
  only:
    - travisci

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g cordova ionic
  - node_modules/karma/bin/karma start ./test-config/karma.conf.js --single-run

script:
  - ionic-app-scripts build --prod